### ISSUE TITLE
2 datatype-expansion problems

### ISSUE THREAD

**Issue by kevinrenskers** [raml-org/datatype-expansion#40] opened 2016-10-14 16:08 UTC
I am using datatype-expansion in raml2obj to deal with inherited types. It's all mostly working, except that when you expand a root type and then get the canonical form, all the types on the properties and stuff are now just a string instead of an array, wheres normally a type is always an array (`['string']`). This makes the types inconsistent and I had to deal with that in raml2obj because in raml2html I don't want to deal with things that are something arrays but something strings. Doing the work in raml2obj to make them consistent works, but seems like the wrong place to fix this :)

There is a much more serious problem though: array types.

So in the [world-music-api](https://github.com/raml-org/raml-examples/tree/master/others/world-music-api) example, there is an `AnotherEntry` type, which in turn has the `Event` type. The `Event` type is of type `array`.

Now when I use the datatype-expansion library, I would expect that `AnotherEntry` is expanded into `'array'`, but instead it's expanded into `['Entry']` and nothing is copied over (expanded). This blocks the `Entry` properties from being shown on anything that uses `AnotherEntry`, because the expansion isn't final.

Hope that makes sense.

**Comment by antoniogarrote** [comment] 2016-10-17 15:43
Hi @kevinrenskers!

I'm trying to reproduce the bug you are reporting. Seems to be working for me.
I have added one spec covering the bug but it doesn't fail:

https://github.com/raml-org/raml-parser-toolbelt/pull/42/files#diff-f5b07c67e024197a8dfbcace28e2883fR396

``` clojure
(deftest world-music-1
  (let [input { "Entry" { :type "array",
                         :items { :type "object",
                                 :properties { :title { :type "string" },
                                              :artist { :type "string" }
                                              }}}
               "AnotherEntry" {:type "Entry"
                               :description "This is just another entry to simulate that you can add facets also on JSON schema defined types. Although you can only add documentation-based facets."}}
        expanded(expanded-form (get input "AnotherEntry") input)
        canonical (canonical-form expanded)]
    (is (= canonical
           {:description "This is just another entry to simulate that you can add facets also on JSON schema defined types. Although you can only add documentation-based facets.",
            :type "array",
            :items {:properties {"title" {:type "string", :required true},
                                 "artist" {:type "string", :required true}},
                    :additionalProperties true,
                    :type "object"}}))))
```

Can you give me some more details?

Cheers.

**Comment by kevinrenskers** [comment] 2016-10-17 16:31
Okay, here is a test. It's a bit long because of all the boilerplate involved.

``` javascript
const raml = require('raml-1-parser');
const tools = require('datatype-expansion');
const assert = require('assert');

const source = './test/world-music-api/api.raml';

function _arrayToObject(arr) {
  return arr.reduce((acc, cur) => {
    Object.keys(cur).forEach((key) => {
      acc[key] = cur[key];
    });
    return acc;
  }, {});
}

raml.loadApi(source, { rejectOnErrors: true }).then((result) => {
  if (result._node._universe._typedVersion === '0.8') {
    throw new Error('_sourceToRamlObj: only RAML 1.0 is supported!');
  }

  return result.expand(true).toJSON({ serializeMetadata: false });
}).then((obj) => {
  // First check that our type is just the raw unexpanded type
  const body = obj.resources[1].methods[0].responses[200].body['application/json'];
  assert(body.type[0] === 'AnotherEntry');

  // Make the types array of objects into a normal object
  const types = _arrayToObject(obj.types);

  // Expand all the types
  Object.keys(types).forEach((key) => {
    tools.expandedForm(types[key], types, (err, expanded) => {
      if (expanded) {
        tools.canonicalForm(expanded, (err, canonical) => {
          if (canonical) {
            types[key] = canonical;
          }
        });
      }
    });
  });

  // Now assign the properties of the newly expanded types into our body
  Object.assign(body, types.AnotherEntry);

  // And make sure we get type array
  console.log(body.type[0]);
  assert(body.type[0] === 'array');

  console.log('All tests passed!');
});
```

That second test does not pass because the type is not `array` but `Entry`. 

Pretty sure it's due to some errors generated by `tools.canonicalForm`. If you log out the err parameter on line 35 you see stuff like `No method in multimethod 'datatype-expansion.canonical-form/lt' for dispatch value: ["json" "json"]`.

**Comment by antoniogarrote** [comment] 2016-11-01 11:20
Hi @kevinrenskers I finally got some time to look into this, sorry for my late reply.

I have checked the actual RAML API and the problem is slightly different, `Entry` and `AnotherEntry` in the world-music API are not array types, they are foreign JSON-Schema types.
The JSON schema is actually describing an array as you mentioned, but the type expansion algorithms don't support the conversion from JSON-Schema into a RAML type. They treat them as just another type of scalar type, like string or integer.
You will need to pre-process the types to transform them into native RAML types if you want to use them with the data-expansion / canonical form functionality. I'm doing that myself in a number of projects and most of the times the conversion is straightforward.

Having said that, there was actually a bug in the expansion code when you are inheriting from JSON or XML type. That was making your code fail, throwing an error when you were invoking the canonical form on the expanded version of `AnotherEntry`. Unfortunately you didn't have any error handling logic so you were thinking it was computing an incorrect canonical form, when it was simply failing and not replacing the original type.
Version 0.14, fixes this particular problem.

Also notice that the output of expanding/canonilising a RAML type produces an output that is slightly different from the spec. It creates a type with `type` facet 'json' and a `content` facet with the raw JSON for the type.

I have added a test for your use case that shows the expected output, please take a look:

``` clojure
(deftest json-types-inheritance
  (let [input {"Entry" {:name "Entry",
                        :displayName "Entry"
                        :type ["{\n  \"type\": \"array\",\n  \"items\": {\n    \"$ref\": \"#/definitions/song\"\n  },\n  \"definitions\": {\n    \"song\": {\n      \"type\": \"object\",\n      \"properties\": {\n        \"title\": {\n          \"type\": \"string\"\n        },\n        \"artist\": {\n          \"type\": \"string\"\n        }\n      }\n    }\n  }\n}\n"]
                        :required true}
               "AnotherEntry" {:name "AnotherEntry"
                               :displayName "AnotherEntry"
                               :type ["Entry"]
                               :required true
                               :description "This is just another entry to simulate that you can add facets also on JSON\nschema defined types. Although you can only add documentation-based facets.\n"}}
        canonical-entry (-> (get input "Entry") (expanded-form input) canonical-form)
        modified-input (assoc input "Entry" canonical-entry)
        expanded (expanded-form (get input "AnotherEntry") modified-input)
        canonical (canonical-form expanded)]
    (is (= canonical
           {:description "This is just another entry to simulate that you can add facets also on JSON\nschema defined types. Although you can only add documentation-based facets.\n",
            :displayName "AnotherEntry",
            :content "{\n  \"type\": \"array\",\n  \"items\": {\n    \"$ref\": \"#/definitions/song\"\n  },\n  \"definitions\": {\n    \"song\": {\n      \"type\": \"object\",\n      \"properties\": {\n        \"title\": {\n          \"type\": \"string\"\n        },\n        \"artist\": {\n          \"type\": \"string\"\n        }\n      }\n    }\n  }\n}\n",
            :name "AnotherEntry",
            :type "json",
            :required true}))))
```

I'm closing this ticket.

**Closed as completed** 2016-11-01 11:20 UTC

**Comment by kevinrenskers** [comment] 2016-11-01 11:28
Thanks, I'll look into this. NPM still has version 0.0.12, will you publish the new one?

**Comment by kevinrenskers** [comment] 2016-11-01 12:19
Tested and it works great! This is now part of raml2obj & raml2html.
