### ISSUE TITLE
Still ['type'] vs 'type' inconsistencies.

### ISSUE THREAD

**Issue by kevinrenskers** [raml-org/datatype-expansion#43] opened 2016-11-21 12:23 UTC
This is what I reported in an earlier ticket:

"I am using datatype-expansion in raml2obj to deal with inherited types. It's all mostly working, except that when you expand a root type and then get the canonical form, all the types on the properties and stuff are now just a string instead of an array, wheres normally a type is always an array (['string'])."

This is sadly still happening.

Test one: array of Foo.

```
#%RAML 1.0
title: Test
description: Test of array support
version: v1
baseUri:
  value: https://exmaple.com/{version}
protocols: HTTPS
mediaType: application/json

types:
  Foo:
    properties:
      id: string
  Foos: Foo[]

/foos:
  get:
    responses:
      200:
        body: Foos
```

After parsing and datatype expansion, the type of the body is `'array'`.

Test two: array of string, so no datatype expansion is happening.

```
#%RAML 1.0
title: API used to test broken features
version: v1
baseUri: http://api.samplehost.com/broken/{version}
mediaType: application/json
protocols: [HTTP, HTTPS]

/:
  get:
    responses:
      200:
        body:
          type: string[]
          example: ["somevalue","anothervalue"]
```

The type of body is `['array']`. This is what I would indeed expect.

It's the datatype expansion which ends up creating a different type of type: string instead of array. This makes the overall output extremely hard to work with for tools like raml2obj and raml2html.

**Comment by kevinrenskers** [comment] 2016-11-21 12:24
It is **very** important for tools like raml2obj and raml2html that we have consistent "stuff" to work with. Types that are sometimes an array and sometimes not are really the worst to work with.

**Comment by kevinrenskers** [comment] 2016-11-21 12:29
I get that the whole idea of the datatype expansion is that multiple inherited types get reduced into one single type with the properties and stuff expanded into it, and so it does make sense that the type ends up being a string. But since the base raml parser does not return the same type of types (it always returns arrays), that makes it inconsistent.

It would be so much better if the datatype expansion would be integrated into the actual parser so that ALL types would ALWAYS be a string, but until we're at that point, how can we deal with this problem?

**Comment by antoniogarrote** [comment] 2016-11-21 15:40
Hi @kevinrenskers, thanks for your comments.

If I got the problem correctly, you are computing the canonical form for some types in the output of a particular RAML parser, and the output of the canonical form does not match the way that parser outputs type information for the remaining nodes.
In particular, the problem is that types in the output of the RAML parser are always JSON arrays and the type of a canonical type is always a string.

Unfortunately I'm afraid that changing the canonical form is not an option. Reducing the value of `type` to a string value is part of the definition of the [canonical form](https://github.com/raml-org/raml-parser-toolbelt/blob/master/tools/datatype-expansion/doc/algorithms.md#canonical-form), and it was defined like that with a clear number of use cases in mind.

The easiest solution might be to expand all the types in the output model of your parser. In this way you should have a consistent output for the types, but you will lose the inheritance relationship information, as well as the type aliases.

If this is not a solution for your use case, I guess that's because you need to keep that information, but you also need to compute inheritance. In this case I would try to keep both outputs and a mapping between them, or to compute the canonical form dynamically, so I can use for each use case one form or the other when needed.

I'm sorry, I don't know raml2obj or raml2html to have a better understanding of the context. I'll try to take a look.

**Comment by kevinrenskers** [comment] 2016-11-21 20:55
I am now walking through the entire object graph and making all types consistent (always a string), that seems to work. It's just a pity that this work is necessary :)

**Comment by antoniogarrote** [comment] 2016-11-24 00:17
I agree, but I'm not involved in the parser (in fact, the data type expansion code is extracted from a custom Clojure parser).

Closing the issue for now.

**Closed as completed by antoniogarrote** 2016-11-24 00:17 UTC
